/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialVestingModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cUSDT"
      | "claim"
      | "claimedAmount"
      | "cliffTimestamp"
      | "confidentialProtocolId"
      | "createVest"
      | "hasSchedule"
      | "paymentGate"
      | "totalAmount"
      | "vestingDuration"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "VestingClaimed" | "VestingCreated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "cUSDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "claim", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimedAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cliffTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVest",
    values: [AddressLike, BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSchedule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentGate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingDuration",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "cUSDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cliffTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createVest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasSchedule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingDuration",
    data: BytesLike
  ): Result;
}

export namespace VestingClaimedEvent {
  export type InputTuple = [beneficiary: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [beneficiary: string, timestamp: bigint];
  export interface OutputObject {
    beneficiary: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingCreatedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    cliffTimestamp: BigNumberish,
    vestingDuration: BigNumberish
  ];
  export type OutputTuple = [
    beneficiary: string,
    cliffTimestamp: bigint,
    vestingDuration: bigint
  ];
  export interface OutputObject {
    beneficiary: string;
    cliffTimestamp: bigint;
    vestingDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialVestingModule extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialVestingModule;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialVestingModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cUSDT: TypedContractMethod<[], [string], "view">;

  claim: TypedContractMethod<[], [void], "nonpayable">;

  claimedAmount: TypedContractMethod<
    [beneficiary: AddressLike],
    [string],
    "view"
  >;

  cliffTimestamp: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createVest: TypedContractMethod<
    [
      beneficiary: AddressLike,
      totalAmount: BytesLike,
      cliffTimestamp: BigNumberish,
      vestingDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  hasSchedule: TypedContractMethod<
    [beneficiary: AddressLike],
    [boolean],
    "view"
  >;

  paymentGate: TypedContractMethod<[], [string], "view">;

  totalAmount: TypedContractMethod<
    [beneficiary: AddressLike],
    [string],
    "view"
  >;

  vestingDuration: TypedContractMethod<
    [beneficiary: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cUSDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedAmount"
  ): TypedContractMethod<[beneficiary: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "cliffTimestamp"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createVest"
  ): TypedContractMethod<
    [
      beneficiary: AddressLike,
      totalAmount: BytesLike,
      cliffTimestamp: BigNumberish,
      vestingDuration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasSchedule"
  ): TypedContractMethod<[beneficiary: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentGate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalAmount"
  ): TypedContractMethod<[beneficiary: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "vestingDuration"
  ): TypedContractMethod<[beneficiary: AddressLike], [bigint], "view">;

  getEvent(
    key: "VestingClaimed"
  ): TypedContractEvent<
    VestingClaimedEvent.InputTuple,
    VestingClaimedEvent.OutputTuple,
    VestingClaimedEvent.OutputObject
  >;
  getEvent(
    key: "VestingCreated"
  ): TypedContractEvent<
    VestingCreatedEvent.InputTuple,
    VestingCreatedEvent.OutputTuple,
    VestingCreatedEvent.OutputObject
  >;

  filters: {
    "VestingClaimed(address,uint256)": TypedContractEvent<
      VestingClaimedEvent.InputTuple,
      VestingClaimedEvent.OutputTuple,
      VestingClaimedEvent.OutputObject
    >;
    VestingClaimed: TypedContractEvent<
      VestingClaimedEvent.InputTuple,
      VestingClaimedEvent.OutputTuple,
      VestingClaimedEvent.OutputObject
    >;

    "VestingCreated(address,uint256,uint256)": TypedContractEvent<
      VestingCreatedEvent.InputTuple,
      VestingCreatedEvent.OutputTuple,
      VestingCreatedEvent.OutputObject
    >;
    VestingCreated: TypedContractEvent<
      VestingCreatedEvent.InputTuple,
      VestingCreatedEvent.OutputTuple,
      VestingCreatedEvent.OutputObject
    >;
  };
}
