/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConfidentialYieldVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LOCK_DURATION"
      | "YIELD_DIVISOR"
      | "cUSDT"
      | "claimWithYield"
      | "confidentialProtocolId"
      | "deposit"
      | "getDeposit"
      | "getDepositTimestamp"
      | "hasDeposit"
      | "paymentGate"
      | "unlockTime"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Claimed" | "Deposited"): EventFragment;

  encodeFunctionData(
    functionFragment: "LOCK_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "YIELD_DIVISOR",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cUSDT", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimWithYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositTimestamp",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentGate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockTime",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "LOCK_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "YIELD_DIVISOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cUSDT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimWithYield",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentGate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unlockTime", data: BytesLike): Result;
}

export namespace ClaimedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [user: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [user: string, timestamp: bigint];
  export interface OutputObject {
    user: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialYieldVault extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialYieldVault;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialYieldVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LOCK_DURATION: TypedContractMethod<[], [bigint], "view">;

  YIELD_DIVISOR: TypedContractMethod<[], [bigint], "view">;

  cUSDT: TypedContractMethod<[], [string], "view">;

  claimWithYield: TypedContractMethod<[], [void], "nonpayable">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [user: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;

  getDeposit: TypedContractMethod<[user: AddressLike], [string], "view">;

  getDepositTimestamp: TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  hasDeposit: TypedContractMethod<[user: AddressLike], [boolean], "view">;

  paymentGate: TypedContractMethod<[], [string], "view">;

  unlockTime: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LOCK_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YIELD_DIVISOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cUSDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimWithYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [user: AddressLike, amount: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getDepositTimestamp"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasDeposit"
  ): TypedContractMethod<[user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentGate"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unlockTime"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getEvent(
    key: "Claimed"
  ): TypedContractEvent<
    ClaimedEvent.InputTuple,
    ClaimedEvent.OutputTuple,
    ClaimedEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;

  filters: {
    "Claimed(address,uint256)": TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;
    Claimed: TypedContractEvent<
      ClaimedEvent.InputTuple,
      ClaimedEvent.OutputTuple,
      ClaimedEvent.OutputObject
    >;

    "Deposited(address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
  };
}
