/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace FlowRegistry {
  export type RouteConfigStruct = {
    yieldPct: BigNumberish;
    vestPct: BigNumberish;
    liquidPct: BigNumberish;
  };

  export type RouteConfigStructOutput = [
    yieldPct: bigint,
    vestPct: bigint,
    liquidPct: bigint
  ] & { yieldPct: bigint; vestPct: bigint; liquidPct: bigint };
}

export interface FlowRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "getRoute"
      | "hasCustomRoute"
      | "resetRoute"
      | "setRoute"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "RouteConfigReset" | "RouteConfigSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoute",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasCustomRoute",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetRoute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRoute",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRoute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasCustomRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resetRoute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setRoute", data: BytesLike): Result;
}

export namespace RouteConfigResetEvent {
  export type InputTuple = [sender: AddressLike];
  export type OutputTuple = [sender: string];
  export interface OutputObject {
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteConfigSetEvent {
  export type InputTuple = [
    sender: AddressLike,
    yieldPct: BigNumberish,
    vestPct: BigNumberish,
    liquidPct: BigNumberish
  ];
  export type OutputTuple = [
    sender: string,
    yieldPct: bigint,
    vestPct: bigint,
    liquidPct: bigint
  ];
  export interface OutputObject {
    sender: string;
    yieldPct: bigint;
    vestPct: bigint;
    liquidPct: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FlowRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): FlowRegistry;
  waitForDeployment(): Promise<this>;

  interface: FlowRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getRoute: TypedContractMethod<
    [sender: AddressLike],
    [FlowRegistry.RouteConfigStructOutput],
    "view"
  >;

  hasCustomRoute: TypedContractMethod<[sender: AddressLike], [boolean], "view">;

  resetRoute: TypedContractMethod<[], [void], "nonpayable">;

  setRoute: TypedContractMethod<
    [yieldPct: BigNumberish, vestPct: BigNumberish, liquidPct: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoute"
  ): TypedContractMethod<
    [sender: AddressLike],
    [FlowRegistry.RouteConfigStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasCustomRoute"
  ): TypedContractMethod<[sender: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "resetRoute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoute"
  ): TypedContractMethod<
    [yieldPct: BigNumberish, vestPct: BigNumberish, liquidPct: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "RouteConfigReset"
  ): TypedContractEvent<
    RouteConfigResetEvent.InputTuple,
    RouteConfigResetEvent.OutputTuple,
    RouteConfigResetEvent.OutputObject
  >;
  getEvent(
    key: "RouteConfigSet"
  ): TypedContractEvent<
    RouteConfigSetEvent.InputTuple,
    RouteConfigSetEvent.OutputTuple,
    RouteConfigSetEvent.OutputObject
  >;

  filters: {
    "RouteConfigReset(address)": TypedContractEvent<
      RouteConfigResetEvent.InputTuple,
      RouteConfigResetEvent.OutputTuple,
      RouteConfigResetEvent.OutputObject
    >;
    RouteConfigReset: TypedContractEvent<
      RouteConfigResetEvent.InputTuple,
      RouteConfigResetEvent.OutputTuple,
      RouteConfigResetEvent.OutputObject
    >;

    "RouteConfigSet(address,uint8,uint8,uint8)": TypedContractEvent<
      RouteConfigSetEvent.InputTuple,
      RouteConfigSetEvent.OutputTuple,
      RouteConfigSetEvent.OutputObject
    >;
    RouteConfigSet: TypedContractEvent<
      RouteConfigSetEvent.InputTuple,
      RouteConfigSetEvent.OutputTuple,
      RouteConfigSetEvent.OutputObject
    >;
  };
}
