/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVaultDeposit } from "./IVaultDeposit";
export type { IVestingCreate } from "./IVestingCreate";
export type { MockGate } from "./MockGate";
