/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ZamaConfig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZamaConfig__factory>;
    getContractFactory(
      name: "ZamaEthereumConfig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZamaEthereumConfig__factory>;
    getContractFactory(
      name: "FhevmECDSA",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FhevmECDSA__factory>;
    getContractFactory(
      name: "FHE",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FHE__factory>;
    getContractFactory(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IKMSVerifier__factory>;
    getContractFactory(
      name: "IACL",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IACL__factory>;
    getContractFactory(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IFHEVMExecutor__factory>;
    getContractFactory(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IInputVerifier__factory>;
    getContractFactory(
      name: "ConfidentialPaymentGate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConfidentialPaymentGate__factory>;
    getContractFactory(
      name: "IConfidentialVestingModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IConfidentialVestingModule__factory>;
    getContractFactory(
      name: "IConfidentialYieldVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IConfidentialYieldVault__factory>;
    getContractFactory(
      name: "ConfidentialVestingModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConfidentialVestingModule__factory>;
    getContractFactory(
      name: "ConfidentialYieldVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ConfidentialYieldVault__factory>;
    getContractFactory(
      name: "FlowRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FlowRegistry__factory>;
    getContractFactory(
      name: "IERC7984Minimal",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC7984Minimal__factory>;
    getContractFactory(
      name: "MockERC7984",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC7984__factory>;
    getContractFactory(
      name: "IVaultDeposit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVaultDeposit__factory>;
    getContractFactory(
      name: "IVestingCreate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVestingCreate__factory>;
    getContractFactory(
      name: "MockGate",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockGate__factory>;

    getContractAt(
      name: "ZamaConfig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZamaConfig>;
    getContractAt(
      name: "ZamaEthereumConfig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ZamaEthereumConfig>;
    getContractAt(
      name: "FhevmECDSA",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FhevmECDSA>;
    getContractAt(
      name: "FHE",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FHE>;
    getContractAt(
      name: "IKMSVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IKMSVerifier>;
    getContractAt(
      name: "IACL",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IACL>;
    getContractAt(
      name: "IFHEVMExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IFHEVMExecutor>;
    getContractAt(
      name: "IInputVerifier",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IInputVerifier>;
    getContractAt(
      name: "ConfidentialPaymentGate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConfidentialPaymentGate>;
    getContractAt(
      name: "IConfidentialVestingModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IConfidentialVestingModule>;
    getContractAt(
      name: "IConfidentialYieldVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IConfidentialYieldVault>;
    getContractAt(
      name: "ConfidentialVestingModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConfidentialVestingModule>;
    getContractAt(
      name: "ConfidentialYieldVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ConfidentialYieldVault>;
    getContractAt(
      name: "FlowRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FlowRegistry>;
    getContractAt(
      name: "IERC7984Minimal",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC7984Minimal>;
    getContractAt(
      name: "MockERC7984",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC7984>;
    getContractAt(
      name: "IVaultDeposit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVaultDeposit>;
    getContractAt(
      name: "IVestingCreate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IVestingCreate>;
    getContractAt(
      name: "MockGate",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockGate>;

    deployContract(
      name: "ZamaConfig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZamaConfig>;
    deployContract(
      name: "ZamaEthereumConfig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZamaEthereumConfig>;
    deployContract(
      name: "FhevmECDSA",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FhevmECDSA>;
    deployContract(
      name: "FHE",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IKMSVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "ConfidentialPaymentGate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialPaymentGate>;
    deployContract(
      name: "IConfidentialVestingModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfidentialVestingModule>;
    deployContract(
      name: "IConfidentialYieldVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfidentialYieldVault>;
    deployContract(
      name: "ConfidentialVestingModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialVestingModule>;
    deployContract(
      name: "ConfidentialYieldVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialYieldVault>;
    deployContract(
      name: "FlowRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlowRegistry>;
    deployContract(
      name: "IERC7984Minimal",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7984Minimal>;
    deployContract(
      name: "MockERC7984",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC7984>;
    deployContract(
      name: "IVaultDeposit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultDeposit>;
    deployContract(
      name: "IVestingCreate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVestingCreate>;
    deployContract(
      name: "MockGate",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockGate>;

    deployContract(
      name: "ZamaConfig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZamaConfig>;
    deployContract(
      name: "ZamaEthereumConfig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ZamaEthereumConfig>;
    deployContract(
      name: "FhevmECDSA",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FhevmECDSA>;
    deployContract(
      name: "FHE",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FHE>;
    deployContract(
      name: "IKMSVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IKMSVerifier>;
    deployContract(
      name: "IACL",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IACL>;
    deployContract(
      name: "IFHEVMExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IFHEVMExecutor>;
    deployContract(
      name: "IInputVerifier",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IInputVerifier>;
    deployContract(
      name: "ConfidentialPaymentGate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialPaymentGate>;
    deployContract(
      name: "IConfidentialVestingModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfidentialVestingModule>;
    deployContract(
      name: "IConfidentialYieldVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IConfidentialYieldVault>;
    deployContract(
      name: "ConfidentialVestingModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialVestingModule>;
    deployContract(
      name: "ConfidentialYieldVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ConfidentialYieldVault>;
    deployContract(
      name: "FlowRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FlowRegistry>;
    deployContract(
      name: "IERC7984Minimal",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC7984Minimal>;
    deployContract(
      name: "MockERC7984",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC7984>;
    deployContract(
      name: "IVaultDeposit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVaultDeposit>;
    deployContract(
      name: "IVestingCreate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IVestingCreate>;
    deployContract(
      name: "MockGate",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockGate>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
