/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialYieldVault,
  IConfidentialYieldVaultInterface,
} from "../../../contracts/ConfidentialPaymentGate.sol/IConfidentialYieldVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConfidentialYieldVault__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialYieldVaultInterface {
    return new Interface(_abi) as IConfidentialYieldVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialYieldVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfidentialYieldVault;
  }
}
