/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IConfidentialVestingModule,
  IConfidentialVestingModuleInterface,
} from "../../../contracts/ConfidentialPaymentGate.sol/IConfidentialVestingModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "totalAmount",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "cliffTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vestingDuration",
        type: "uint256",
      },
    ],
    name: "createVest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IConfidentialVestingModule__factory {
  static readonly abi = _abi;
  static createInterface(): IConfidentialVestingModuleInterface {
    return new Interface(_abi) as IConfidentialVestingModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IConfidentialVestingModule {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IConfidentialVestingModule;
  }
}
