/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultDeposit,
  IVaultDepositInterface,
} from "../../../contracts/MockGate.sol/IVaultDeposit";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "amount",
        type: "bytes32",
      },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVaultDeposit__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultDepositInterface {
    return new Interface(_abi) as IVaultDepositInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVaultDeposit {
    return new Contract(address, _abi, runner) as unknown as IVaultDeposit;
  }
}
