/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVestingCreate,
  IVestingCreateInterface,
} from "../../../contracts/MockGate.sol/IVestingCreate";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "euint64",
        name: "totalAmount",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "cliffTimestamp",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vestingDuration",
        type: "uint256",
      },
    ],
    name: "createVest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVestingCreate__factory {
  static readonly abi = _abi;
  static createInterface(): IVestingCreateInterface {
    return new Interface(_abi) as IVestingCreateInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVestingCreate {
    return new Contract(address, _abi, runner) as unknown as IVestingCreate;
  }
}
